### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [attie/libxbee3#13]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) in the function "[libxbee::ConCallback::libxbee_callbackFunction](https://github.com/attie/libxbee3/blob/bc2dae498c3009e7aa50e1124988200f877e436a/xbeep.cpp#L321)".

**Comment by attie** [comment]
fixed as-of 73fdcae

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/attie/libxbee3/commit/73fdcaec190bba0567b87d3a683638187589960b).
