### ISSUE TITLE
Digi Xbee Pro S1 test module problem

### ISSUE THREAD

**Issue by venushkadharmasiri** [attie/libxbee3#15]
I have checked my Xbee pro s1 module on xXCTU is working I tried the test program But i'm not having the incorrect output. Please be kind enough to explain me.

```
venushka-pc@venushkapc-ThinkPad-E460:~/my_libxbee/libxbee3/sample/xbee1/0.simple_at$ make 
gcc main.c -g -o main -I/home/venushka-pc/my_libxbee/libxbee3/include -L /home/venushka-pc/my_libxbee/libxbee3/lib -lxbee -lpthread -lrt
venushka-pc@venushkapc-ThinkPad-E460:~/my_libxbee/libxbee3/sample/xbee1/0.simple_at$ ./main 
tx: -17
txRet: 0
```

**Comment by attie** [comment]
Hello,

Please work through the "it's not working" steps on my website:

http://attie.co.uk/libxbee/getting_started/its_not_working#s1

It would be particularly useful for you to enable logging, as discussed on
that page.

Attie

**Comment by venushkadharmasiri** [comment]
Dear Attie,

I've sloved it your library is working. Thank you so much.
