### ISSUE TITLE
open(): No such file or directory

### ISSUE THREAD

**Issue by gokul96** [attie/libxbee3#22]
running a XbeeZB board, raspberry pi, raspbian jessie,

make and install for library completed

trying to run /sample/3.simpledata

make
chmod a+x main
./main

>> open (): no such file or directory
ret: -6 (an I/O request failed)

why does this happen how to fix it ?

**Comment by attie** [comment]
Look at the source, make sure that device exists :-)

**Comment by gokul96** [comment]
Checked source, device exists,
In main function it gets stuck at
if((ret=xbee_setup(.....,"/dev/ttyUSB0",9600.....)


Regards,

Gokul Pothirajan
gokul.pothirajan@gmail.com
+919094962312

**Comment by attie** [comment]
Please run: `ls -l /dev/tty*` and post the output.
Please also include a complete snippet of your source from around the call to `xbee_setup()`

**Comment by gokul96** [comment]
>>crw-rw-rw- 1 root tty       5,  0 Feb 21 13:58 /dev/tty
crw--w---- 1 root tty       4,  0 Feb 21 13:58 /dev/tty0
crw------- 1 pi   tty       4,  1 Feb 21 14:19 /dev/tty1
crw--w---- 1 root tty       4, 10 Feb 21 13:58 /dev/tty10
crw--w---- 1 root tty       4, 11 Feb 21 13:58 /dev/tty11
crw--w---- 1 root tty       4, 12 Feb 21 13:58 /dev/tty12
crw--w---- 1 root tty       4, 13 Feb 21 13:58 /dev/tty13
crw--w---- 1 root tty       4, 14 Feb 21 13:58 /dev/tty14
crw--w---- 1 root tty       4, 15 Feb 21 13:58 /dev/tty15
crw--w---- 1 root tty       4, 16 Feb 21 13:58 /dev/tty16
crw--w---- 1 root tty       4, 17 Feb 21 13:58 /dev/tty17
crw--w---- 1 root tty       4, 18 Feb 21 13:58 /dev/tty18
crw--w---- 1 root tty       4, 19 Feb 21 13:58 /dev/tty19
crw--w---- 1 root tty       4,  2 Feb 21 13:58 /dev/tty2
crw--w---- 1 root tty       4, 20 Feb 21 13:58 /dev/tty20
crw--w---- 1 root tty       4, 21 Feb 21 13:58 /dev/tty21
crw--w---- 1 root tty       4, 22 Feb 21 13:58 /dev/tty22
crw--w---- 1 root tty       4, 23 Feb 21 13:58 /dev/tty23
crw--w---- 1 root tty       4, 24 Feb 21 13:58 /dev/tty24
crw--w---- 1 root tty       4, 25 Feb 21 13:58 /dev/tty25
crw--w---- 1 root tty       4, 26 Feb 21 13:58 /dev/tty26
crw--w---- 1 root tty       4, 27 Feb 21 13:58 /dev/tty27
crw--w---- 1 root tty       4, 28 Feb 21 13:58 /dev/tty28
crw--w---- 1 root tty       4, 29 Feb 21 13:58 /dev/tty29
crw--w---- 1 root tty       4,  3 Feb 21 13:58 /dev/tty3
crw--w---- 1 root tty       4, 30 Feb 21 13:58 /dev/tty30
crw--w---- 1 root tty       4, 31 Feb 21 13:58 /dev/tty31
crw--w---- 1 root tty       4, 32 Feb 21 13:58 /dev/tty32
crw--w---- 1 root tty       4, 33 Feb 21 13:58 /dev/tty33
crw--w---- 1 root tty       4, 34 Feb 21 13:58 /dev/tty34
crw--w---- 1 root tty       4, 35 Feb 21 13:58 /dev/tty35
crw--w---- 1 root tty       4, 36 Feb 21 13:58 /dev/tty36
crw--w---- 1 root tty       4, 37 Feb 21 13:58 /dev/tty37
crw--w---- 1 root tty       4, 38 Feb 21 13:58 /dev/tty38
crw--w---- 1 root tty       4, 39 Feb 21 13:58 /dev/tty39
crw--w---- 1 root tty       4,  4 Feb 21 13:58 /dev/tty4
crw--w---- 1 root tty       4, 40 Feb 21 13:58 /dev/tty40
crw--w---- 1 root tty       4, 41 Feb 21 13:58 /dev/tty41
crw--w---- 1 root tty       4, 42 Feb 21 13:58 /dev/tty42
crw--w---- 1 root tty       4, 43 Feb 21 13:58 /dev/tty43
crw--w---- 1 root tty       4, 44 Feb 21 13:58 /dev/tty44
crw--w---- 1 root tty       4, 45 Feb 21 13:58 /dev/tty45
crw--w---- 1 root tty       4, 46 Feb 21 13:58 /dev/tty46
crw--w---- 1 root tty       4, 47 Feb 21 13:58 /dev/tty47
crw--w---- 1 root tty       4, 48 Feb 21 13:58 /dev/tty48
crw--w---- 1 root tty       4, 49 Feb 21 13:58 /dev/tty49
crw--w---- 1 root tty       4,  5 Feb 21 13:58 /dev/tty5
crw--w---- 1 root tty       4, 50 Feb 21 13:58 /dev/tty50
crw--w---- 1 root tty       4, 51 Feb 21 13:58 /dev/tty51
crw--w---- 1 root tty       4, 52 Feb 21 13:58 /dev/tty52
crw--w---- 1 root tty       4, 53 Feb 21 13:58 /dev/tty53
crw--w---- 1 root tty       4, 54 Feb 21 13:58 /dev/tty54
crw--w---- 1 root tty       4, 55 Feb 21 13:58 /dev/tty55
crw--w---- 1 root tty       4, 56 Feb 21 13:58 /dev/tty56
crw--w---- 1 root tty       4, 57 Feb 21 13:58 /dev/tty57
crw--w---- 1 root tty       4, 58 Feb 21 13:58 /dev/tty58
crw--w---- 1 root tty       4, 59 Feb 21 13:58 /dev/tty59
crw--w---- 1 root tty       4,  6 Feb 21 13:58 /dev/tty6
crw--w---- 1 root tty       4, 60 Feb 21 13:58 /dev/tty60
crw--w---- 1 root tty       4, 61 Feb 21 13:58 /dev/tty61
crw--w---- 1 root tty       4, 62 Feb 21 13:58 /dev/tty62
crw--w---- 1 root tty       4, 63 Feb 21 13:58 /dev/tty63
crw--w---- 1 root tty       4,  7 Feb 21 13:58 /dev/tty7
crw--w---- 1 root tty       4,  8 Feb 21 13:58 /dev/tty8
crw--w---- 1 root tty       4,  9 Feb 21 13:58 /dev/tty9
crw-rw---- 1 root dialout 204, 64 Feb 21 13:58 /dev/ttyAMA0
crw------- 1 root root      5,  3 Feb 21 13:58 /dev/ttyprintk
crw-rw---- 1 root dialout 188,  0 Feb 21 13:58 /dev/ttyUSB0

USB0 is the xbee board

>>int main(void) {
void *d;
struct xbee *xbee;
struct xbee_con *con;
struct xbee_conAddress address;
xbee_err ret;
printf("hello1");
if ((ret = xbee_setup(&xbee, "xbeeZB", "/dev/ttyUSB0",9600 )) !=
XBEE_ENONE) {
printf("ret: %d (%s)\n", ret, xbee_errorToStr(ret));
printf("hello2");
return ret;
}

snippet around the error
even hello1 does not get printed

**Comment by gokul96** [comment]
i have re-verified that xbee's are properly configured in API mode and can
communicate with each other

**Comment by attie** [comment]
`stdout` is line buffered, which means that you won't typically see the message unless you either:
1. end the line (with `\n`)
2. call `fflush(stdout)`

So, please change the `printf("hello1");` / `printf("hello2");` into `printf("hello1\n");` / `printf("hello2\n");` and run again.

It does look like `/dev/ttyUSB0` exists, but could you check:
1. that you are a member of the dialout group (run `id -Gn` and post the output) - if not you _should_ be seeing a different error.
2. that you can actually use this tty with another program (e.g: minicom)
