### ISSUE TITLE
How to get RSSI using C++ library?

### ISSUE THREAD

**Issue by cafeclimber** [attie/libxbee3#29]
Using the C++ Library with an XBee1. I can get RSSI using the C library, but the rest of my project is in C++ and would like to remain consistent. Thanks

**Comment by attie** [comment]
Hello Ryan,

Please try the attached patch.
If this works out, then please let me know and I'll commit it.

Attie

**Comment by cafeclimber** [comment]
Hi Attie,

Unfortunately I didn't see any attachment to the issue, or the e-mail. 

I was able to get RSSI by editing the library directly to include a getRssi() function to xbeep then rebuilding the library. I didn't know if this really fit with the codebase or I would've submitted a pull request :)

**Comment by attie** [comment]
Oops, apologies... I sent an email, and I think github removed the attachment.

Please see the [cpp_rssi_access](https://github.com/attie/libxbee3/tree/cpp_rssi_access) branch. Sounds like I did the same thing as you.

**Comment by cafeclimber** [comment]
Yup. Basically the same thing. Thanks!
