### ISSUE TITLE
Callback for any remote address

### ISSUE THREAD

**Issue by skalkoto** [attie/libxbee3#34]
Hello, 

How can I create a callback in C++ or C that will be called if a packet from any address arrives? I could only find a way to create a callback for a specific unicast address or broadcast, but not any address. How is my module supposed to communicate with an other modules that has sent data to it It doesn't a priori know its address?

**Comment by attie** [comment]
You can use the [`catchAll`](https://github.com/attie/libxbee3/blob/master/include/xbee.h#L107) flag.

See the catch-all example for more info: [`./sample/xbee1/8.catch-all/main.c`](https://github.com/attie/libxbee3/blob/master/sample/xbee1/8.catch-all/main.c)

**Comment by skalkoto** [comment]
Works! Thanks a lot.
