### ISSUE TITLE
Retrieve the MAC address of a module

### ISSUE THREAD

**Issue by skalkoto** [attie/libxbee3#37]
Hello,

Is there a way to retrieve the mac-address of a module? I python you can just call `get_64bit_addr()` on the device after you open it. What about in libxbee3?

Thank you in advance,
Nikos

**Comment by attie** [comment]
What are you trying to do?

### Get a local module's address - e.g: ATSH and ATSL
The 64-bit address of the local device must be retrieved using a `Local AT` connection - [this example](https://github.com/attie/libxbee3/blob/master/sample/xbee1/1.simple_at/main.c#L71) will get the device's `NI` / "Node Identifier"... you can swap this for `SH` and `SL`.

### Get a remote module's address - e.g: from an incoming message
The 64-bit address of a remote device is available in the [`xbee_conAddress`](https://github.com/attie/libxbee3/blob/master/include/xbee.h#L84) structure, in the [`xbee_pkt`](https://github.com/attie/libxbee3/blob/master/include/xbee.h#L145) structure - e.g:

    pkt->address.addr64[]

**Comment by skalkoto** [comment]
I was referring to the local module. The `Local AT` connection should do. Thanx a lot.

**Comment by attie** [comment]
No problem!
