### ISSUE TITLE
typedef redefinition with different types

### ISSUE THREAD

**Issue by betsman** [attie/libxbee3#39]
During the installation of libxbee3 on MAC OSX 10.13.4,  I get the following error and 5 warnings. 

![1error](https://user-images.githubusercontent.com/20289362/39806887-417a7c1e-537b-11e8-9ac0-d42f01e276cb.jpeg)

Does somebody know how to fix this error? Many thanks for the help in advance!!!

**Comment by bjaury** [comment]
Betsman I am experiencing the same issue. Were you able to resolve this issue?

**Comment by attie** [comment]
It looks like OSX has updated their headers since I last looked... does removing the offending lines from the libxbee code base get things going?
