### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by akhenakh** [attie/libxbee3#7]
I'm trying to use libxbee3 on OSX 10.10 (works ok on Linux).

For example generic/3.log hangs:

```
ioctl(0x2, 0x4004667A, 0x7FFF5786E80C)       = 0 0
sem_open(0x1083C516B, 0xA00, 0x1B6)      = 259 0
sem_unlink(0x1083C516B, 0xA00, 0x1B6)        = 0 0
sem_open(0x1083C516B, 0xA00, 0x1B6)      = 260 0
sem_unlink(0x1083C516B, 0xA00, 0x1B6)        = 0 0
```

 Is it supported?
Thanks

**Comment by attie** [comment]
It has been used on OSX in the past... are you familiar enough with a debugger to see where it's hung?
I don't have easy access to a Mac I'm afraid...

**Comment by akhenakh** [comment]
seems to hung on open()
at xsys_darwin.c:60

```
-> 60       if ((info->dev.fd = open(info->device, O_RDWR | O_NOCTTY | O_SYNC)) == -1) {
```

**Comment by akhenakh** [comment]
Was using `/dev/tty.usbserial-A40081lA` it works with `/dev/cu.usbserial-A40081lA`.

Weird sorry for the false alarm !

**Comment by attie** [comment]
Ah, yes... There is a note on the bottom of this page: http://attie.co.uk/libxbee/getting_started/os/osx#s2

Would it have helped to put it elsewhere too?

**Comment by akhenakh** [comment]
I miss that one, great doc!

Maybe move some of your website into github cause users probably expect for it to be on github?
thank you

**Comment by attie** [comment]
I've added a note to the man pages (and thus HTML pages).
You can view a hosted version here: http://doc.libxbee.attie.co.uk/man3/xbee_setup.3.html

**Comment by akhenakh** [comment]
It may help some :)
