### ISSUE TITLE
Transmission Times out After a While Randomly

### ISSUE THREAD

**Issue by mahsu** [attie/libxbee3#8]
Hello,

I'm currently trying to send data using the `xbee_connTx(...)` method to send data between two series three XBees, both at 57600 baud on an Ubuntu 13.04. The code that I am using can be found [here](https://github.com/CURocketry/LaunchVehicleController2016/blob/c127752cb3e664ce98da45a721671853de15d45e/src/main.c). I have been testing with the XBees stationary and right next to each other.

The transmission code is roughly as follows:

```
for (;;) {
    /* do stuff to the buffer */
    if ((ret = xbee_connTx(con, &retVal, buf_start, buf_size)) != XBEE_ENONE) {
        if (ret == XBEE_ETX) {
            printf("tx error (0x%02X)\n", retVal);
        } else {
            printf("error: %s\n", xbee_errorToStr(ret));
        }
    }
    usleep(500000); //500ms
```

   }

I'm currently running into an issue where, inconsistently after a few hundred transmissions or so, transmission returns an error of `XBEE_ETIMEOUT`. It works again if I terminate the program and restart it. Each time, the number of transmissions that go through vary: sometimes 50 might work, other times >300. Even though transmission is timing out, packets can still be successfully received.

I have already tried:
- Increasing/decreasing the delay in the infinite loop. (50ms-1000ms)
- Sending only one byte at a time.
- Disabling and enabling ACK.

I saw your documentation on [status reports](http://attie.co.uk/libxbee/func_overview#connection-oriented_interface_) and have figured out that the semaphore in [xbee_framewait](https://github.com/attie/libxbee3/blob/bc2dae498c3009e7aa50e1124988200f877e436a/frame.c#L130) is timing out after the default 1 second, but I am not sure how to further debug the issue or what the root cause might be.

Any help would be greatly appreciated!

**Comment by attie** [comment]
Hello,

Please could you enable debugging (see #7 here
http://attie.co.uk/libxbee/getting_started/its_not_working).
It's important that and XBEE_LOG_RX are XBEE_LOG_TX enabled.

I'm interested to see if there is any communication between libxbee and the
XBee module, or if this stops completely (my suspicion).

Please re-run your application, and attach the log output.

Attie
